export const LABORATORY_TASKS = [
  "Seysmik faol hududlarda quriladigan aktiv seysmik himoyalash qurilmalariga ega bo'lgan va ega bo'lmagan yuqori qavatli binolarning konstruktiv o'ziga xosliklarini inobatga olgan holda seysmik mustahkamligini hisoblash usullarini takomillashtirish.",
  "Bino va inshootlarning texnik holatini monitoring qilishning ilmiy asoslarini yaratish bo'yicha tadqiqotlar o'tkazish. Zilzilalarda bino va inshootlarning shikastlanish darajasini baholash hamda ilmiy hajmdor ishlanmalarni ishlab chiqish.",
  "Bino va inshootlarni seysmik himoyalash uslublarini, yangi konstruktiv yechimlarni hamda ko'p qavatli bino va inshootlarning seysmik xatarini baholash metodikasini ishlab chiqish.",
  "Bino va inshootlarning zilzilabardoshlik bo'yicha texnik holatini baholashning zamonaviy uslublarini ishlab chiqish, shuningdek, ularning texnik holatini tadqiq qilish, barcha turdagi bino va inshootlarni instrumental-texnik tekshiruvdan o'tkazish.",
  "Grunt bilan o'zaro ta'sirni va konstruktiv o'ziga xosliklarni hisobga olgan holda yerosti va yerusti inshootlari zilzilabardoshligi nazariyalarini rivojlantirish.",
  'Gruntlar mexanikasi va geotexnika tadqiqotlarini rivojlantirish, qurilish materiallarini tajribalar orqali sinash.',
  "Suv omborlarining texnik holatiga ta'sir etuvchi turli omillarni inobatga olgan holda uning seysmik mustahkamligini aniqlashga qaratilgan tadqiqotlar olib borish.",
  "Yangi qurilish materiallarining fizik-mexanik xossalarini, konstruksiyalar mustahkamligini tadqiq qilish hamda olingan natijalar asosida amaldagi texnik jihatdan tartibga solish sohasidagi normativ hujjatlarni takomillashtirish bo'yicha takliflar ishlab chiqish.",
  '"Yashil" qurilish texnologiyalarini amaliyotga joriy etish. Qurilishda energiya tejamkor materiallar va uslublardan foydalanishni tadqiq qilish. Muqobil energiya manbalaridan (quyosh, shamol, biomassa va boshqalar) foydalanish bo\'yicha ilmiy izlanishlar olib borish.',
  'Energiya samaradorligini oshirishga qaratilgan texnologiyalarni sinovdan o\'tkazish. "Yashil" qurilish standartlari va normativlarini ishlab chiqishda ishtirok etish. Ekologik barqarorlikni ta\'minlashga xizmat qiluvchi loyihalarni ishlab chiqish va tadqiq etish.',
  "Qurilish sohasida sun'iy intellekt texnologiyalaridan foydalanish va raqamli qurilishni rivojlantirish, barqaror konstruktiv yechimlar olish bo'yicha tadqiqotlar o'tkazish.",
  "Barqaror konstruktiv tizimlar bo'yicha tadqiqot olib borish, shaharsozlik tizimlari va infratuzilmani rivojlantirish bo'yicha dasturlar tayyorlash.",
  'Yerosti va yerusti shaharsozligi va infratuzilma muammolarini yechishga qaratilgan ilmiy takliflar ishlab chiqish.',
  "Qurilishda texnik jihatdan tartibga solish sohasidagi normativ hujjatlarni yangi ishlanmalar va yuqori texnologiyalarni inobatga olgan holda takomillashtirish bo'yicha tavsiyalar ishlab chiqish.",
  "Respublika aholisi va hududining seysmik xavfsizligini ta'minlash, o'rta va uzoq istiqbolda bino va inshootlar hamda muhandislik infratuzilmalarini seysmik xavfdan himoya qilishning strategik yo'nalishlarida dasturlarni tayyorlashda ishtirok etish.",
  "Sohada fan va ta'lim integratsiyasini ta'minlash maqsadida o'quv dasturlari va uslubiy qo'llanmalar hamda monografiyalar tayyorlash, yuqori malakali kadrlar tayyorlashda, kadrlar malakasini oshirish va qayta tayyorlashda ishtirok etish.",
  'Ilmiy tadqiqotlar va innovatsion ishlanmalarning natijalarini tijoratlashtirish.',
  "Xalqaro ilmiy-texnik hamkorlikni rivojlantirish, chet el universitetlari, ilmiy-tadqiqot markazlari va institutlari bilan qo'shma tadqiqotlarda ishtirok etish, tegishli ilmiy yo'nalishlar va ixtisosliklar bo'yicha ilmiy darajali kadrlar tayyorlash.",
] as const;
